### ISSUE TITLE
Autocomplete needs to contain full set of annotatable gene products

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/simple-annoton-editor#18]
The autocomplete for gene products will need to include the same set of annotatable gene products as the graphical editor.

I've just tried entering the following strings for autocomplete and do not get any resulting matches:

- daf-16

- WB:WBGene00000912

- dpp

- dpp Dmel

- FB:FBgn0000490

- wee1 (trying to find a pombe gene; autocomplete presents human and pig wee gene products)

- wee1 Spom

- PomBase:SPCC18B5.03

All of those searches match the correct entity in the graphical editor.

**Comment by tmushayahama** [comment]
Changed closure  to CHEBI:23367 from CHEBI:33695. Now all the genes should show up.
