### ISSUE TITLE
Allow annotation to root nodes

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/simple-annoton-editor#20]
Curators should be able to create annotations to the root nodes of each aspect of the ontology.

molecular_function (GO:0003674)
biological_process (GO:0008150)
cellular_component (GO:0005575)

**Comment by tmushayahama** [comment]
For root node, select the more option button (ellipsis button "...") then choose from the drop down menu
![image](https://user-images.githubusercontent.com/2273929/36834139-b4185f0a-1ce6-11e8-9436-5396a4eded30.png)
was fixed https://github.com/geneontology/simple-annoton-editor/commit/8ac08dfa33aedc0fd755ac6c99cc21a66a920e19 and https://github.com/geneontology/simple-annoton-editor/commit/0e39aca41ac125a901b12b87dd7d2e1f7693f5e9
