### ISSUE TITLE
Display unique id or accession along with gene product name and species

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/simple-annoton-editor#22]
To clarify for curators what entity they are annotating, we will need to also display the unique id or accession associated with the gene name and species.

**Comment by tmushayahama** [comment]
Isn't it the model id displayed on top-left of the page? Or they want something to uniquely identify an activity within the model?

**Comment by thomaspd** [comment]
This refers to what is displayed in the form for a gene product.  Right now, only the label is shown, and we want the label plus the identifier.  For example, right now you show "ABCA1 Hsap", but the curators want to see "ABCA1 Hsap (UniProtKB:O95477)".

This applies to the form, and to the view of the activities in the model at the bottom of the page.

**Comment by tmushayahama** [comment]
Now the Gene Product and Macromolecular Complex input will show label (id) once you select from the dropdown
