### ISSUE TITLE
With entries need to populate the evidence on the graph nodes

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/simple-annoton-editor#23]
Entering values in the With field of the SAE does not populate the corresponding With field in the evidence section of the corresponding node of the graph view.

Also note that With entries may be comma- or pipe-separated and that formatting will need to be preserved in the graph view as well.

**Comment by tmushayahama** [comment]
I have added the "with" and is now being added to the graph. However, for now, I am not validating or checking if the pattern is in the format "PREFIX:ID, +". It is just treated as a text. Will close it for now but will add validations to all fields in form.

**Comment by cmungall** [comment]
Note the underlying datamodel doesn't support disjunctions of Withs (pipes), only conjunctions (commas).

One hacky option is simply to store the boolean expression as a string using the GAF syntax
