### ISSUE TITLE
Will need to add model annotation toggle for form input

### ISSUE THREAD

**Issue by kltm** [geneontology/simple-annoton-editor#29]
As it stands right now, all new models in Noctua, unless otherwise specified, are set to default to `development` status (as a model annotation). While this can be manually toggled in the graph editor all form editors will also need the ability to model models through the various status states. Specifically, `development` and `production`.

**Comment by tmushayahama** [comment]
Done in SAE https://github.com/geneontology/simple-annoton-editor/commit/c076010639739b2248015363017caf0360a1a287
