### ISSUE TITLE
Form should check for incorrect reference formatting and not allow annotations to be made if references are not entered correctly

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/simple-annoton-editor#30]
The proper format for references in a GO annotation is:

DB:accession_number

All values entered into the Reference field should be checked for that format and annotations should be flagged with an error message and not created in the model if the Reference entry does not conform to that syntax.

I will also add this same ticket to the Noctua tracker, as the graphical interface should have a check for this, as well.

**Comment by tmushayahama** [comment]
@vanaukenk I have added the reference and with check 'DB:accession_number', However it doesn't further check if a particular DB exists or a particular accession_number exists. e.g. WRONG_DB:1234 will pass. Should I check this also? Is there a known list of Databases?

**Comment by thomaspd** [comment]
@vanaukenk - can this be closed now?
