### ISSUE TITLE
Merge the fork back into the upstream repo

### ISSUE THREAD

**Issue by kltm** [geneontology/simple-annoton-editor#31]
Switching repos is a bit difficult for looking at what is currently going on on noctua-dev. As the current fork is the only active development, it needs to be folded back into the upstream geneontology repo.

As well, it seems like the compiled component is not included in the current fork. Workbenches should always include the properly pathed compiled component for use. (With the compiled component push on separate commits than the changing code.)

**Comment by tmushayahama** [comment]
Have made a dev branch on SAE https://github.com/geneontology/simple-annoton-editor/commit/ab80333dedb003c8deb36fc5442d013d46288b8e
