### ISSUE TITLE
Make additional evidence added visible in the editor

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/simple-annoton-editor#38]
It is very nice to be able to add additional evidence and references to an annotation, but it would be more helpful to curators if they could actually see all of the evidence and references they've added.

Right now, only the first combination of evidence and reference is displayed.

Thx.

**Comment by tmushayahama** [comment]
@vanaukenk I was struggling on how to display it on the SAE Form without overpopulating. The functionality is a bit hidden (steps below). On the main form only the first one is shown. 
Any suggestions on this?

**Click More Evidence**

![image](https://user-images.githubusercontent.com/2273929/37312830-df215a72-2609-11e8-9e43-ada197771955.png)

**Then you can add more** 

![image](https://user-images.githubusercontent.com/2273929/37312870-008a62da-260a-11e8-8105-5e486eb11b69.png)

**Comment by thomaspd** [comment]
If I understand correctly, it would be good to have a visual cue showing that there is more than one piece of evidence for a triple.  Would it be possible to add a small text button next to the word "Evidence" that says "See all evidence", whenever there are multiple pieces of evidence.  Clicking on the button would bring up the pop-up the same way as choosing "More evidence" already does.

**Comment by tmushayahama** [comment]
If there is more than one evidence a "+n evidence" button will show as  below

![image](https://user-images.githubusercontent.com/2273929/38434157-408e3826-3982-11e8-861e-8e5296ced242.png)

Clicking this button will take you to the all evidence page where you can add or remove

@vanaukenk any suggestions on this one.
