### ISSUE TITLE
Warn (prevent?) users if the model contains edges that could potentially be lost

### ISSUE THREAD

**Issue by cmungall** [geneontology/simple-annoton-editor#4]
the SAM only covers a subset of expressivity of GO-CAMs. If a model contains extra info, e.g. causal linkages, these can be lost if any edits are made in the SAM.

Minimally the SAM should say: be careful editing existing models

Ideally, the SAM would detect if the model contains any edges untranslatable to simple annotons and warn if these are present.

**Comment by kltm** [comment]
As well, it should be noted that when "editing" an annoton in this tool, currently it is destroyed and replaced. It is also possible to mine out the entities and replace them with new class expressions, but it take a little more work.
