### ISSUE TITLE
incorrect assumption in SAE on CC extensions entered in graph

### ISSUE THREAD

**Issue by krchristie** [geneontology/simple-annoton-editor#40]
In this model, I have entered component annotations with cell component extensions via the graph.

http://68.181.125.145:8910/editor/graph/gomodel:5a98684700000110

However, the SAE is giving me an error saying that it expected a GO ID. I have used the part_of relationship between the two individuals as I've been taught to do for some time for this type of cell type extension. This relationship makes sense to me as Dnah11 is involved in an unspecified MF that is part of the axoneme which is part of a respiratory epithelial cell. 

[The second set of individuals on the graph with DNAH11 Hsap is a duplicate with fake data to confirm the issue with the Dnah11 Mmus annotations).

**Comment by krchristie** [comment]
The same problem exists for anatomy term extensions, whether using EMAPA (see Dnah9 Mmus annotation) or Uberon (see Dnah2 Mmus annotation).

**Comment by tmushayahama** [comment]
@krchristie let me check it and I will be back with full answer. I am assuming in CC Only, there is no root MF (molecular_function). CC Only was described as **GP part_of CC part_of Cell Type part_of Uberon**. @thomaspd can you comment on this.
in the meantime @kltm can you save Karen's model since this is a development environment it might disappear soon http://68.181.125.145:8910/editor/graph/gomodel:5a98684700000110

**Comment by thomaspd** [comment]
Hi Karen,

Your model isn't valid because it specifies that an MF (an occurrent) is part of a tissue (a continuant).  You've already connected an MF to a CC term using occurs_in.  You just need to connect the tissue term to the CC term (instead of the MF) using part of.

**Comment by krchristie** [comment]
@thomaspd - If you do this in the graph editor by making an annoton for the gene product being in an axoneme, and then adding an individual for the cell type or anatomy term, this is what you get.

Exploding out to separate the terms is entirely impractical as it's just too time consuming to find the right terms and connect them correctly.

**Comment by thomaspd** [comment]
Understood.  The SAE form should make it much easier to make a valid model.

**Comment by tmushayahama** [comment]
@krchristie @thomaspd We can leverage the SAE User Interface to communicate with the user to why the model is not valid. This can also serve as "training" a user to make valid models and understanding how to correct them. Ways of communication might be
- having a detailed error message
- a correct example
- a link to a similar example 
- a link to documentation 
- different coloring of the SAE model other than red. 

For the implementation @goodb @balhoff @cmungall @kltm, can a reasoner be possibly used later.

**Comment by kltm** [comment]
@tmushayahama Any models that need to be saved can be downloaded from within the graph editor (Model -> Export OWL) and you can create a PR in noctua-models/dev. E.g:
http://68.181.125.145:8910/download/gomodel:5a98684700000110/owl

**Comment by tmushayahama** [comment]
I can close this for now
