### ISSUE TITLE
Option for another level of CC nesting

### ISSUE THREAD

**Issue by thomaspd** [geneontology/simple-annoton-editor#42]
From @vanaukenk @krchristie - Sometimes a curator will want two levels of CC nesting, e.g.
MF occurs_in CC1 part_of CC2 (optionally with part_of CL, part_of Uberon/anatomy)

Suggestion would be to add another option under the "..." button on the CC line (in both the "Default" and "CC only" forms), with a pop-up where someone can add a second CC annotation

**Comment by tmushayahama** [comment]
@thomaspd by 2 levels do you mean skipping CC? Where is the second CC annotation?

**Comment by thomaspd** [comment]
No, I mean adding another part_of CC line, kind of like what we're doing now for BP (where BP1 part_of BP2 part_of BP3).  So there would be a second CC (CC2), linked to the first one (CC1, the one currently in the form) with part_of.

But I thought that since it's not a very common workflow, instead of adding another line to the form for CC2, we'd have a popup instead.

**Comment by tmushayahama** [comment]
@thomaspd So something like below (I was using cc1 for CL and CC2 for UB, that is why I got confused). Number of dashes represents nesting level, and the **bold** will be optional

MF
-CC
**--CC1
---CC2**
--CL
---UB
-

**Comment by thomaspd** [comment]
Just one more level of CC (CC2):
MF
-CC
--CC2
---CL
----UB

**Comment by tmushayahama** [comment]
@thomaspd now I see. thanks. I will put it quickly, however the only challenge will be to read the activity (error message). It will say "wrong ontology, CC, expecting CL." on node CC1

**Comment by thomaspd** [comment]
Yes, that's right.  You'll need to allow CC part_of CC, in addition to CC part of CL or CC part of UB

**Comment by cmungall** [comment]
Are we expecting fixed levels? I think all but the first CC should be optional.

E.g.

 * CC-CL: an `axon` that is part of a `neuron`
 * CC-CL-AN: an `axon` that is part of a `neuron` that is part-of a 'hippocampus`
 * CC-CC2-CL: an `axoneme` that is part of a `motile-cilium` that is part of a `respiratory epithelial cell`
 * CC-CC2-CL-AN: an `axoneme` that is part of a `motile-cilium` that is part of a `respiratory epithelial cell` that is part-of a `bronchus`

2 levels of AN are not unheard of. This is often not required, as too much detail is counter-productive and fake (e.g. processes in the skin of the hand may not be so different from homologous processes in the skin of the foot). Additionally, in Uberon there is a lot of ready-made precomposed terms, but we have to work in a multi-AO environment here and not all AOs are the same. So I want to say let's not allow this but I'm sure someone will come and prove us wrong..

**Comment by tmushayahama** [comment]
@thomaspd any comment on the above.

**Comment by thomaspd** [comment]
@cmungall - No need to worry, the levels above are not fixed.  The levels I put in were just to illustrate the maximally nested case (number 4 in your list), using the terminology familiar to Tremayne.  We already allow (and will continue to allow) missing fields, and the filled in ones will be connected directly to each other.  So all the cases you listed, plus others like CC-AN are also allowed.

**Comment by krchristie** [comment]
I think it is a great idea to be able to put in another level of CC nesting. I'm not even sure I'd say it's a rare workflow. My perception is that I do it frequently. 

It is less common for me to nest two anatomy terms. I can't even think of an example when I've done this. I do frequently use both a CL term and an anatomy term, but I can' think when I've used two anatomy terms.

But if we are making it possible to add an extra level of nesting, it seems like it would be a good idea to make it generally applicable to anything you want to add beyond the default options.

Also, while I don't really mind that much if it shows up as a popup when you first enter it, I have a marginal preference for adding a new row and would definitely want it to show up as a row in the SAE entry form so that I see EVERYTHING I am putting into the annoton before I hit save.

**Comment by thomaspd** [comment]
Thanks Karen, sounds good.  We'll put another level of CC nesting in the form by default.

**Comment by krchristie** [comment]
It doesn't have to be default, as long as it's easy to add the extra level when needed.

**Comment by tmushayahama** [comment]
Will close this. nested view has been added
