### ISSUE TITLE
link in SAE to get to graphical editor of same model

### ISSUE THREAD

**Issue by krchristie** [geneontology/simple-annoton-editor#44]
This wasn't really necessary in the older version of Noctua since you had to go back up to the top level to start a new model anyway.

However, now that you can start a new model from the SAE, I find it really frustrating that I can not easily get from the SAE to the graphical editor for the model I am currently entering annotations on. I would really like to be able to open the corresponding graphical view of the model I am currently working on in the SAE directly from the SAE, preferably into a new window, like when you open the SAE from the graphical editor

**Comment by tmushayahama** [comment]
To go to graphical editor and other conveniences, click view and click link. A new tab will appear 

![image](https://user-images.githubusercontent.com/2273929/38750356-87228b84-3f09-11e8-8792-d09416ab0b69.png)

**Comment by krchristie** [comment]
Thanks!
