### ISSUE TITLE
Annotating when cellular component is unknown but anatomy or cell type is known

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/simple-annoton-editor#51]
If a curator has information about the cell type or anatomical structure in which a gene is expressed, but not the subcellular localization, do we want them to be able to annotate this in the SAE?

If so, should this be handled in a similar way as we handle an unknown MF, i.e. we populate the root CC node using evidence supporting the cell or anatomical term annotation?

This would allow filtering of these root CC annotations from the GPAD output like we are doing for the MF annotations.

**Comment by tmushayahama** [comment]
@vanaukenk @krchristie Can you check if all the skip combinations are working for both default and ccOnly

**Comment by vanaukenk** [comment]
@tmushayahama 
I can now skip individual CC fields in the default editor and it will allow me to enter the annoton, and the display is correct in the graph editor.  
However, I still get an error message in the summary table when I just enter one GO term and then a cell type.  It seems the summary table is still expecting the first entry below the CC term to be another CC term.  Are you still working on that part?
Here's the test model:
http://68.181.125.145:8910/editor/graph/gomodel:5ae3d45e00000111

**Comment by krchristie** [comment]
I've just tried three different annotons, in this model: 
http://68.181.125.145:8910/workbench/simple-annoton-editor/?model_id=gomodel:5ae3d45e00001425 

They all look good to me, both in the graph and the SAE Table View. Although I see error colors flash onto the new Table View rows briefly, they disappear after a second or two.

**Comment by vanaukenk** [comment]
Yes, this seems to be working well now.  Thx.
One minor issue wrt the table view is that, to be consistent with the MF part of the form that also allows skipping, the different rows should all be left-justified in the CC part of the form.
