### ISSUE TITLE
Searching ontology synonyms

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/simple-annoton-editor#53]
It would be helpful if the GO term autocomplete allowed for searching on synonyms.

The display would include both the main term name and the synonym, perhaps something like this if the curator searched for 'receptor binding':

GO:0005102 signaling receptor binding (syn: receptor binding)

This is a more general issue and may relate to this ticket here:
https://github.com/geneontology/noctua/issues/257

**Comment by tmushayahama** [comment]
@cmungall @kltm @thomaspd any comment on this?

**Comment by kltm** [comment]
This is supported by the backend. The issue is likely with the hard-coded queries in the code that you inherited.

**Comment by tmushayahama** [comment]
@kltm the graph doesn't do it either

**Comment by kltm** [comment]
It is in AmiGO and AFAICT it works in Noctua too, at least in some cases.
"Cajal body" (http://amigo.geneontology.org/amigo/term/GO:0015030) can be found in the "Add individual" autocomplete with the synonym "Gems". Similarly in the "Add annoton" cellular_component autocomplete.

**Comment by thomaspd** [comment]
From the curators, was the request for synonyms for ontology terms, or was it for gene name synonyms?  I think it might be for gene names/symbols.

**Comment by vanaukenk** [comment]
The original request was for ontology term synonyms.  
In Seth's case of searching on 'Gems' the 'Cajal body' synonym is found in the form, the graph, and AmiGO.
In the use case that led to this ticket, though, we were searching with 'receptor binding' which didn't get us to 'signaling receptor binding' but maybe this is because the list of terms that contains the 'receptor binding' string in name, synonyms or definition is long while the list of terms containing 'Gems' in the name, synonyms or definition is very short.
