### ISSUE TITLE
String added to With/From field in summary table even when nothing entered in the form

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/simple-annoton-editor#57]
The summary view at the bottom added a string to the With/From field for a BP annotation even when I didn't enter anything in the form for that field.  See the second line in the table:

![image](https://user-images.githubusercontent.com/1730534/38813279-837c0ba4-415c-11e8-84c4-b0d1167c7a3a.png)

**Comment by tmushayahama** [comment]
@vanaukenk @krchristie  ohh I published that code by mistake (was experimenting). But eventually it will solve this ambiguous  problem 

![image](https://user-images.githubusercontent.com/2273929/38826392-7e0e62d6-4164-11e8-9f0a-87262600af08.png)

In this case we don't know which entity is being annotated for cholesterol homeostasis. So we were gonna use with field to store gomodel id value for annotated entity (gp), but not show it to the user. I think we can make a new ticket for this issue and continue discussion there and @thomaspd can explain more
