### ISSUE TITLE
better error messages

### ISSUE THREAD

**Issue by krchristie** [geneontology/simple-annoton-editor#58]
It's really great that the error messages are now showing up in the Table view of the SAE.

I think that we need to work on making the error messages more comprehensible to curators, and maybe also thinking through what the likely error really was.

Here is a pair of errors I am seeing today, first the annoton with two rows highlighted, and then each of the two error messages when I click the exclamation point:

![20180418-errorflags](https://user-images.githubusercontent.com/10533218/38955667-2fe0d3e4-430a-11e8-9ad5-eb09c49fe367.jpg)

**This first error message:** 

![20180418-errormessage1](https://user-images.githubusercontent.com/10533218/38955673-34187598-430a-11e8-921b-972d37b8af98.jpg)

This is not very human readable when it uses the ID, nor I suspect, is it true that it expected the **root node** of biological process, but rather that it expected **any** BP term. 

1. It would be more human readable if the last phrase said something in words, rather than using an ID.
2. However, the real error here is not that I have selected the wrong GO term, but rather that I have used the wrong relationship. Considering that the autocomplete allows curators to see exactly what term they have selected, it seems much less likely for a curator to have selected the wrong GO term than to have selected the wrong relationship, so when there is a mismatch between the aspect of the GO term and the relationship used, it is probably more likely that the error is in the relationship. So an error message that would accurately tell me what to fix is to tell me that I have incorrectly used the part_of relationship. Modeled after the current error message, that could look something like this:
> **MF part of Cellular Component**: Wrong relationship. Expected 'occurs in'

**The second error message:**

![20180418-errormessage2](https://user-images.githubusercontent.com/10533218/38955678-386a1570-430a-11e8-8b0e-098d863358e3.jpg)

This seems like it actually shouldn't even be an error message.

This is a 'part of' relationship between two CC terms, which is fine. It seems like it is a problem for the error checking to assume the Aspect of the term based on the relationship, rather than use the actual Aspect of the GO term used. If it did that, and had known that this is a 'part of' between two CC terms, this wouldn't even get flagged, and in fact, it disappeared when I corrected the relationship as described above.

I think that the SAE should show the actual aspect of the term that is present, rather than assuming the aspect of the term based on the relationship used. 

Here is a sample model reconstructed to show just these error messages:
http://68.181.125.145:8910/workbench/simple-annoton-editor/?model_id=gomodel:5ac3d47600001092

**Comment by krchristie** [comment]
Here's another example of an error that I think is not telling the curator something useful and is also interfering with something I want to say.

In this model: http://68.181.125.145:8910/editor/graph/gomodel:5ac3d47600001213 
I entered two annotons via the DEFAULT template, and then, using the graph editor, I connected a BP term to a cell type (CL) term within each annoton because I actually want to say that the BP occurs in that cell type:

Here's the graph of the two template entered annots, plus each has an occurs in relationship between a BP term and a CL term:
![20180420-snx10-graph1](https://user-images.githubusercontent.com/10533218/39078673-99ed05d8-44c1-11e8-8368-86ec2e82dff2.jpg)

Here is the SAE table view, showing errors:
![20180420-saetableview](https://user-images.githubusercontent.com/10533218/39078676-9a352b9c-44c1-11e8-844c-6de828a1f3ac.jpg)

Error 1 (ruffle assembly occurs in osteoclast)
![20180420-snx10error2](https://user-images.githubusercontent.com/10533218/39078674-9a0370ca-44c1-11e8-82a8-d6dd1072f129.jpg)

Error 2 (gastric acid secretion occurs in peptic cell)
![20180420-snx10error1](https://user-images.githubusercontent.com/10533218/39078675-9a1b5b36-44c1-11e8-8584-1686049215b0.jpg)

These two above errors of "Not accepted triple" really don't mean anything to a curator. I also don't understand why it isn't accepting that a "BP occurs in a CL". I thought this was how we were supposed to say this.

On the chance that it didn't like the fact that the cell type was connected to both the MF and the BP, I removed the direct link between a MF and the CL term, but the error is unchanged:
![20180420-snx10-graph2](https://user-images.githubusercontent.com/10533218/39078672-99ce05b6-44c1-11e8-9ae2-a950edf37d78.jpg)

**Comment by cmungall** [comment]
On 20 Apr 2018, at 17:57, Karen R Christie wrote:

> These two above errors of "Not accepted triple" really don't mean 
> anything to a curator. I also don't understand why it isn't accepting 
> that a "BP occurs in a CL". I thought this was how we were supposed to 
> say this.

You are correct, this seems like a bug.

**Comment by vanaukenk** [comment]
First error message should be changed to:
"Incorrect association between term and relationship."

**Comment by vanaukenk** [comment]
An example of a new suggestion for the error message:

Incorrect association between 'lipid transporter activity' and 'lipid transport'

Then the image would show the graph view of the triple.

**Comment by vanaukenk** [comment]
Update to 'Incorrect relationship between 'lipid transporter activity' and lipid transport'.'

**Comment by tmushayahama** [comment]
@vanaukenk I think this can be closed. Also thinking, if we assume that all the models are correct. Will there be a need for an error message?

**Comment by vanaukenk** [comment]
@tmushayahama - I think we can close the ticket here, but the issue of curator friendly error messages is something we still need to work on generally wrt Noctua.

I'm willing to bet we have some existing models that will fail shex validation, but I'm not so clear on what our SOP will be for fixing them.  That may depend on the type of error.
