### ISSUE TITLE
Add ability to generate own empty model and iterate to new empty model after save (also change or force title)

### ISSUE THREAD

**Issue by kltm** [geneontology/simple-annoton-editor#6]
As part of a quicker workflow we should be able to directly jump to the form and have it generate a new empty model on the fly, rather than transitioning through an empty model in the graph editor.

As well, once a model is saved, a button should be made available to create/jump to a new empty form of the same type as previously run.

Note that in the Noctua stack, the model title is special in that it is required before a model can be flushed/stored. Currently, the SAE either takes the "parent"'s name or generates its own from the first entries. For the SAE to operate as a "full" client, it needs to be able to have users be able to initialize and manipulate the title.

(This was available in the previous version of the form.)

**Comment by tmushayahama** [comment]
Implemented as start a new model function
