### ISSUE TITLE
behavior of DEFAULT annoton form when CC not filled in

### ISSUE THREAD

**Issue by krchristie** [geneontology/simple-annoton-editor#60]
The DEFAULT form does not seem to be doing the right thing when you have cell type and anatomy context information, but no actual CC term.

In this model, I have tried several times to enter this type of situation using the DEFAULT form (and NOT modifying anything via the graph editor), and none of them have resulted in what I think they should have.
http://68.181.125.145:8910/workbench/simple-annoton-editor/?model_id=gomodel:5ac3d47600001329 

Here is attempt 1 (Snx10), where I think I may have clicked in the first CC blank but realized it was the wrong place for a cell type term, but then left it blank because I did not want to enter a CC term:
![20180425-defaultentryfromnoccbutcontext](https://user-images.githubusercontent.com/10533218/39259253-ce80d908-486a-11e8-804b-c5123a9b3aa3.jpg)

Here is attempt 2 (Shh), where I made sure NOT to click in the first CC blank:
![20180425-defaultentryfromnoccbutcontext-2](https://user-images.githubusercontent.com/10533218/39261604-d844b642-4871-11e8-87a3-6d055d8b3796.jpg)

Here is attempt 3 (Bbs10), where I manually entered a CC term and evidence:
![20180425-defaultentryfromnoccbutcontext-3](https://user-images.githubusercontent.com/10533218/39262676-ebc46430-4874-11e8-8d2c-fd3ec76c710b.jpg)

Here is what showed up in the Table view of the SAE:
![20180425-threeresultsfromnoccbutcontext](https://user-images.githubusercontent.com/10533218/39262677-ebe47900-4874-11e8-8413-efa500923322.jpg)

None of these annotons is displaying correctly in the SAE table view.
- Snx10 - Both the CL term and the EMAPA anatomy terms have been labelled as P(rocess) terms, rather than as extensions of the assumed CC term. The actual BP term "cilium movement" does not even show up here.
- Shh - In this one, the BP term is now showing up correctly as the BP term, but now it is labelling the EMAPA term as a BP extension and the cell type term does not show up at all. 
- Bbs10 - In this one, it is not showing either the cell type or anatomy terms as extensions

Also, the Bbs10 annoton does not look correct in the graph editor
![20180425-threeresultsfromnoccbutcontext-graph](https://user-images.githubusercontent.com/10533218/39263667-bb1ae18a-4877-11e8-9b86-330549e547f7.jpg)
 
since it not made a connection between the MF enabled by Bbs10 entity and the CL and anatomy terms. (The Rbpj present in the model but not shown in the screen shot is a duplicate to confirm that the missing connection is not an error on my part in moving the terms around on the graph).

**Comment by krchristie** [comment]
The error messages shown in the SAE Table View screenshot above are similar to some I have already described in https://github.com/geneontology/simple-annoton-editor/issues/58, where the error message is inaccurate due to incorrectly assuming what kind of term is present. In this case though, all of these CL and EMAPA terms were entered in the correct locations within the DEFAULT form and appear to have not been correctly assigned as extensions of the root CC term.

**Comment by tmushayahama** [comment]
@vanaukenk @krchristie I have fixed the "if component skipped" part  https://github.com/geneontology/simple-annoton-editor/issues/51 and the error message will continue ithere https://github.com/geneontology/simple-annoton-editor/issues/58
