### ISSUE TITLE
With/From field needs to allow for multiple entries

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/simple-annoton-editor#63]
Curators may need to enter multiple values in the With/From field.
These values may be either comma- or pipe-separated.
Maintaining the comma or pipe is essential for correctly interpreting the meaning of the entry, i.e. treat the entries as text and copy exactly how the curator enters the value(s).
In either case, if there is more than one With/From value, all values should appear in the same line in the annotation (summary table, graph editor, and annotation preview).

**Comment by tmushayahama** [comment]
Added the with as a string. So far no validations

**Comment by vanaukenk** [comment]
Thanks @tmushayahama 
I've tested two WB entries and they look okay.

**Comment by tmushayahama** [comment]
@vanaukenk let's link this one to the proposed with field constraint
