### ISSUE TITLE
Clone evidence option should require evidence code and reference before populating list

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/simple-annoton-editor#64]
It is currently possible to enter an evidence code with no reference and have that option show up in the list of possible evidence to clone.

I found this out by entering an evidence code and then remembering that I could just clone the evidence.

Without removing the original evidence code, I went to the clone evidence list and now had two entries to choose from, one with the paper reference and one without.  The entry without the paper should not be allowed on the list.

**Comment by krchristie** [comment]
I noticed this yesterday and agree that evidence lines shouldn't show up in the clone options unless they are complete. I did exactly the same thing Kimberly did, where I had entered an evidence code and then remembered I could clone instead.

**Comment by vanaukenk** [comment]
If the user opens the clone evidence window, whatever evidence exists on the line should be cleared.

**Comment by krchristie** [comment]
This looks good to me. Thanks @tmushayahama

**Comment by vanaukenk** [comment]
@tmushayahama - also closing this issue as it appears to be working correctly now.  Thx.
