### ISSUE TITLE
issues with new format of gene identifiers

### ISSUE THREAD

**Issue by krchristie** [geneontology/simple-annoton-editor#66]
Hi,

I noticed that the display of gene product IDs has changed from the way it used to look, which I liked a lot since it displayed the gene name, and then showed the MOD ID, in this case from MGI, parenthetically:
![20180426-6-tableviewshowingmissingalleleid](https://user-images.githubusercontent.com/10533218/39726850-4a4a370c-5205-11e8-99ea-1285fff66605.jpg)

However, today, when entering new annotations, I am getting this longer and less human readable display:
![20180507-bponly-sae-tv](https://user-images.githubusercontent.com/10533218/39726799-2877d274-5205-11e8-843b-e865d95fae9f.jpg)

In addition, older models (e.g. http://68.181.125.145:8910/editor/graph/gomodel:5ae3d45e00000619), now fail to translate the MGI ID for the gene product into the gene symbol and are giving me errors for "GP enables MF" and "MF part_of BP" triples:
![20180507-previouslyenteredgp-ids-nottranslated](https://user-images.githubusercontent.com/10533218/39727023-ebf3b8e4-5205-11e8-98ac-d8db37657a04.jpg)

**Comment by krchristie** [comment]
Also, this new ID format is too long in the pulldown menu for GPs in the SAE, such that I cannot see the actual gene symbol to even know what I am selecting: 

![20180507-newidformat-pulldownmenu](https://user-images.githubusercontent.com/10533218/39729458-c7d11a82-5210-11e8-8d7b-a728d37a2530.jpg)

Obviously, the software people should be deciding what is going on under the hood, but please do not show me the "_http://identifiers.org/mgi/_" at all. Whatever you choose to put under the hood, please only show curators the part that translates to the database prefix and the ID, e.g. MGI:123456 (or if you have to for MGI considering the choice to have saved the prefix within the ID field, MGI:MGI:123456).

This is probably not the right place for this comment, but I'm putting it here for now, as I do not have time right now to find the right tracker, but the comment about not showing "_http://identifiers.org/mgi/_" portion at all also applies to the pulldown menu for GPs in the Graph, though that one is readable; it is just distracting to have so much identical text that is not useful.

**Comment by kltm** [comment]
@krchristie @tmushayahama We're going to try to re-run the autocomplete system now.

**Comment by kltm** [comment]
I believe this should now be cleared--the load looks good.
@cmungall @yy20716
