### ISSUE TITLE
clicking "START NEW MODEL" leaves original url, instead of changing to reflect new model ID

### ISSUE THREAD

**Issue by krchristie** [geneontology/simple-annoton-editor#69]
This is a little disconcerting if you've been starting new models from the SAE using the START NEW MODEL button, and then want to share one of those subsequent models with another person by copying the url and sending it to them.

Here are the urls: 
**of the first model I was on when I opened the SAE:**
http://68.181.125.145:8910/workbench/simple-annoton-editor/?model_id=gomodel:5ae3d45e00001973 &barista_token=xmib5fvbw4wrweixn8h8

**after clicking START NEW MODEL**
http://68.181.125.145:8910/workbench/simple-annoton-editor/?model_id=gomodel:5ae3d45e00001973 &barista_token=xmib5fvbw4wrweixn8h8

**after naming new model and clicking outside of box**
http://68.181.125.145:8910/workbench/simple-annoton-editor/?model_id=gomodel:5ae3d45e00001973 &barista_token=xmib5fvbw4wrweixn8h8

**after saving a new annoton**
http://68.181.125.145:8910/workbench/simple-annoton-editor/?model_id=gomodel:5ae3d45e00001973 &barista_token=xmib5fvbw4wrweixn8h8

As you can see, the id of the gomodel did not change at all, not even when I had saved annotations into the new model.

It would be really great if the START NEW MODEL button could trigger something to reload the page or whatever is required to change the url to match the new model.

**Comment by tmushayahama** [comment]
@kltm what should I do with one? does replacing gmodel id work?

**Comment by kltm** [comment]
The model id is there for your workbench, to do as is pleases. Depending on how you're running, you may not have access to a new model ID. I would either deprioritize this, as some future update may hide some of that information anyways in some cases, or simply rewrite the URL.

**Comment by vanaukenk** [comment]
This all appears to be working correctly.
