### ISSUE TITLE
Form view does not correspond to graph editor view -> (ref: gomodel:5ae3b0f600000604)

### ISSUE THREAD

**Issue by kltm** [geneontology/simple-annoton-editor#72]
_From @BarbaraCzub on May 24, 2018 17:7_

Hi,

I have 5 annotations displayed in the form view:
![screen shot 2018-05-24 at 18 02 06](https://user-images.githubusercontent.com/16541096/40500418-98bdb6a0-5f7c-11e8-8a93-d1f6221c08ea.png)

But only 3 are displayed in the model:
![screen shot 2018-05-24 at 18 02 58](https://user-images.githubusercontent.com/16541096/40500460-b7b6a166-5f7c-11e8-8dcf-0061c1d24528.png)

Why is this? The 2 which are missing, do actually get displayed in the graph view for the first 1 second after switching to it, but then disappear.

And: how do I delete an annotation from the form view? (The fifth annotation is an identical copy of the fourth one. I added it only as a test, because the fourth annotation was not getting displayed in the graph view, and now I don't know how to remove it - it's not shown in 'Take a Tour').

Thanks,
Barbara

_Copied from original issue: geneontology/noctua-models#95_

**Comment by kltm** [comment]
_From @vanaukenk on May 24, 2018 17:28_

Also, @tmushayahama and @lpalbou are working on adding Delete functionality to the form.  We want to make sure that when curators delete information using the form, the full implications are apparent, i.e. the potential effects on other relations and nodes in a given model.
Does deleting from the graph editor work okay for you in the meantime?

**Comment by BarbaraCzub** [comment]
Thank you @kltm!

And is there a way to navigate from the graph view directly to the form view? 
(In the form view you have the drop down menu, which can be used to navigate to the graph view. But I do not think the opposite is possible?)

**Comment by vanaukenk** [comment]
@BarbaraCzub 
In the graph view, click on the Workbenches menu and then select 'Noctua form' at the very bottom of the list.

**Comment by BarbaraCzub** [comment]
Thank you!

**Comment by vanaukenk** [comment]
There are a number of things in this ticket, but the main issue wrt placement of new nodes seems to be fixed, so I will close the ticket.
For effects of deleting BP nodes, see #94
