### ISSUE TITLE
Confirm most up-to-date annotations are available from Search database function

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/simple-annoton-editor#78]
Hi @tmushayahama 

Today I was working on a model and wanted to see what MF annotations already existed for the C. elegans gene mat-3.

When I used the Search database option, I didn't see any MF annotations available, even though I can see one MF annotation in AmiGO:

http://amigo.geneontology.org/amigo/gene_product/WB:WBGene00003134

Can you double-check to see why that might be?  

Thx!

**Comment by kltm** [comment]
@tmushayahama If you are doing an annotation import, you quite probably want to be using the production GO GOlr servers. I.e.:

http://golr-aux.geneontology.io/ (recommended for bulk operations)
http://golr-aux.geneontology.io/ (the AmiGO UI server)

The NEO/Noctua load does not have annotations.
(I would note that the Function Companion does not use any of the above servers, but another one that is loaded on a different schedule; that is a bug.)

**Comment by kltm** [comment]
If you are trying to do a search of the current public annotations via Solr, that would be the best choice.

**Comment by tmushayahama** [comment]
@kltm what is the solution to the question from @vanaukenk about this endpoint not being up to date? Is function companion up to date?

@vanaukenk when you use the function companion with the same search, what results do you get?

**Comment by vanaukenk** [comment]
@tmushayahama if I use the function companion from the Workbenches menu of the graph editor, and filter on 'mat-3', I do see the protein binding annotation for mat-3 available for import, and importing it seems to work fine.

**Comment by vanaukenk** [comment]
The mat-3 'protein binding' annotation has disappeared from the Search database functionality of the form, although it *is* still accessible from the Function Companion.

**Comment by vanaukenk** [comment]
@tmushayahama - can you confirm that the Search database functionality of the form is searching the current set of production GO annotations?  
@kltm - can the Function Companion and the form Search database functionality please search the same set of annotations?

**Comment by kltm** [comment]
@vanaukenk I'll look into this: geneontology/noctua#586

**Comment by vanaukenk** [comment]
Thank you @kltm !

**Comment by vanaukenk** [comment]
@tmushayahama @kltm 
It looks like this issue still exists.  
I was just trying to add an MF annotation using the Noctua form and can't find the MF I want in the Search database entries, even though that annotation exists in AmiGO, WB, and Protein2GO.
I *can* find the annotation if I use the Function Companion.
@tmushayahama - let's discuss tomorrow.
