### ISSUE TITLE
Spurious GP boxes created if edit and resave

### ISSUE THREAD

**Issue by hdrabkin** [geneontology/simple-annoton-editor#8]
While putting in annotations into table-editor. Made mistake on PMID. Edited in table editor and resaved. Annoton is fine but 4-5 orphan boxes with the gene product symbol were created. Could remove them ok, but is a nuisance. See model gomodel:5993df9e00000631 as example (I left two in, but several more were made.

**Comment by kltm** [comment]
As this model may not survive the restart planned later today, here are some screenshots of the model:

![screenshot_2017-08-25_17-19-18](https://user-images.githubusercontent.com/2687900/29736803-9c1a94d8-89b9-11e7-8d9e-c2a55a9a9f00.png)

![screenshot_2017-08-25_17-18-44](https://user-images.githubusercontent.com/2687900/29736806-a067957c-89b9-11e7-98c2-68791296874f.png)

**Comment by hdrabkin** [comment]
I see today that there are more than just the two from Friday. I suspect that more are created whenever the model is opened?

**Comment by kltm** [comment]
@hdrabkin Unlikely, but other people may have been experimenting and that has caused more individuals to appear. @DoctorBud may be able to answer that.

**Comment by tmushayahama** [comment]
No longer an issue
