### ISSUE TITLE
Allow additional interacting taxon ID

### ISSUE THREAD

**Issue by cmungall** [geneontology/simple-annoton-editor#89]
This is only used when a curator is annotating an inter-species interaction

This will essentially act as an extra level of partonomy:

```
CC -po-> cell type -po-> gross anatomical structure -po-> taxon
```

in practice this will frequently be short-circuited, direct CC to taxon

**Comment by tmushayahama** [comment]
@thomaspd Can you explain this one

**Comment by thomaspd** [comment]
This would be another level of nesting of the CC context.  Right now in the form, it is
MF
occurs in CC
part of CC
part of cell type
part of anatomy

We would add the ability to include one more level of nesting at the end of that chain:
part of organism

It could be implemented in Noctua form under the ... button at the end of any of the fields above (for example "part of CC").  The text could be "Specify interacting organism".  When the user selects this option, another field is added right under the "part of anatomy" line.  The autocomplete of the new field uses the same closure as the "organism" filter in Amigo.  When making this into a model, you would use the same rule as for the other fields in this part of the form: if there are fields above it that are left blank, you connect it (with part of) to the last one that was filled in (and if none are filled in, it gets connected directly to MF using occurs in).

**Comment by vanaukenk** [comment]
This is accounted for in the current specs:

https://github.com/geneontology/GO_Shapes/blob/master/shapes/go-cam-shapes.shex

**Comment by tmushayahama** [comment]
@cmungall @vanaukenk @kltm any idea of how to autocomplete taxon id and short of long taxon names on neo?

**Comment by cmungall** [comment]
I suggest we just do this in a generic fashion. Do not implement any
specific code. Currently the curator must know the 4 letter code but when
we have so many organisms this is unwieldy we will just add synonymy info
to neo

**Comment by vanaukenk** [comment]
@kltm - has confirmed that the NCBI slim taxon is loaded in neo.  What is the source of the NCBI slim taxon?

An alternative source of species information is the BioLink API.  The source of data here would be the species list in AmiGO (annotated species OR ontology taxon slim).

Ideally, curators would be able to autocomplete on taxon id or name or substring of a name.

For now, curators will just copy and past the numerical NCBI taxon ID but, in the future, we will implement autocomplete that will show the label.

**Comment by cmungall** [comment]
(Apologies my previous comment didn't make sense as I thought we were
talking about filtering genes by taxon)

taxslim is the subset used by various ontologies for taxon constraints plus
the set used for manual curation in GO. If we want to be sure any taxon can
be used we can just include the full ncbitaxon in the import chain

**Comment by vanaukenk** [comment]
@tmushayahama - can we close this now that we have organism in the CC annotation extensions on the Noctua 2.0 form?
