### ISSUE TITLE
Add systematic order & sorting to table of annotations in form view

### ISSUE THREAD

**Issue by krchristie** [geneontology/simple-annoton-editor#96]
I am finding it very difficult to be able to check that I have entered all of the annotations that I meant to in Noctua. There does not seem to be any simple way to sort by either annotated gene, or term annotated to.

This is particularly problematic when you have entered a significant number of annotations such as in this model.
ID - gomodel:5c4605cc00003312
Name - SPATA7 maintains photoreceptor-specific distal connecting cilium - PMID:29899041 - KRC

The annotation table in the Form view appears to have a random order, and it's not just that new annotations push older ones down. While I haven't taken notes on this, I often do look for existing annotations in the table so that I can copy them into the form and there is no clear pattern about where in the table the newest annotation will show up, and no systematic order related to either gene name or GO term.

At a minimum, it would be helpful if the both the annotation table in the Form view and the Annotation Preview had a predictable order related to gene name and GO term name. It might be even better if they were sortable.

see also: https://github.com/geneontology/noctua/issues/617

**Comment by tmushayahama** [comment]
Hi @krchristie 

Sorting will be implemented on the new form. In addition, to help table view better, you will be able to collapse each activity. 

**a teaser**
![image](https://user-images.githubusercontent.com/2273929/62153700-050e5f80-b2ba-11e9-9142-03df996e9307.png)

Any other sorting criteria? so far I have gp, mf and recently added.

Tagging @vanaukenk

**Comment by vanaukenk** [comment]
Sort specifications:

Gene product - sort by label

MF - sort by label

Other GO terms - sort by label for BP (directly related to MF) and label for CC (directly related to MF)

Date - sort by value

**Comment by vanaukenk** [comment]
The current iteration of the form (2.0) automatically sorts annotations in the table alphabetically in descending order.  
@tmushayahama - can we close this ticket and any additional sorting requests could be tracked in the noctua-form repo?
